name: Docker Image CI (PGadmin)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PGadmin
        uses: actions/checkout@v4
        with:
          repository: navystack/PGadmin
          path: PGadmin

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_ARM64_RUNNER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_ARM64_RUNNER }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.AMD64_RUNNER_ENDPOINT }}
          append: |
            - endpoint: ${{ secrets.ARM64_RUNNER_ENDPOINT }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./PGadmin/
          file: ./PGadmin/debian.Dockerfile
          push: true
          tags: |
            navystack/pgadmin:bookworm
            navystack/pgadmin:4
          platforms: linux/amd64,linux/arm64
