name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_ARM64_RUNNER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_ARM64_RUNNER }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.AMD64_RUNNER_ENDPOINT }}
          append: |
            - endpoint: ${{ secrets.ARM64_RUNNER_ENDPOINT }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Openresty-modular (1.25.3)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: bookworm/openresty-modular/latest.Dockerfile
          tags: |
            navystack/openresty:1.25.3.1
            navystack/openresty:1.25.3
            navystack/openresty:latest
          platforms: |
            linux/amd64
            linux/arm64


      - name: Nginx-modular (Master)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: bookworm/nginx-modular/latest.Dockerfile
          tags: |
            navystack/ngx_mod:debian-latest
            navystack/ngx_mod:bookworm-latest
            navystack/ngx_mod:1.25.4
            navystack/ngx_mod:latest
          platforms: |
            linux/amd64
            linux/arm64